catalogs:
  actions:
    '@actions/core': ^2.0.2
    '@actions/github': ^9.0.0
  build:
    terser: ^5.46.0
    tsup: ^8.5.1
    typescript: ^5.9.3
  ci:
    '@commitlint/cli': ^20.3.1
    '@commitlint/config-conventional': ^20.3.1
    '@favware/cliff-jumper': ^6.0.0
    husky: ^9.1.7
    lint-staged: ^16.2.7
  core:
    '@npm/types': ^2.1.0
    '@types/bun': ^1.3.6
    commander: ^14.0.2
  lint:
    '@nanoforge-dev/utils-eslint-config': ^1.0.1
    '@nanoforge-dev/utils-prettier-config': ^1.0.1
    '@trivago/prettier-plugin-sort-imports': ^6.0.2
    eslint: ^9.39.2
    prettier: ^3.8.0

onlyBuiltDependencies:
  - esbuild
